env: sc2_v2

env_args:
  # default
  step_mul: 8
  move_amount: 2
  difficulty: "7"
  game_version: null
  seed: null
  continuing_episode: False
  obs_all_health: True
  obs_own_health: True
  obs_last_action: False
  obs_pathing_grid: False
  obs_terrain_height: False
  obs_instead_of_state: False
  obs_timestep_number: False
  obs_starcraft: True
  conic_fov: False
  num_fov_actions: 12
  state_last_action: True
  state_timestep_number: False
  reward_sparse: False
  reward_only_positive: True
  reward_death_value: 10
  reward_win: 200
  reward_defeat: 0
  reward_negative_scale: 0.5
  reward_scale: True
  reward_scale_rate: 20
  use_unit_ranges: False
  min_attack_range: 2
  kill_unit_step_mul: 2
  fully_observable: False
  replay_dir: ""
  replay_prefix: ""
  heuristic_ai: False
  heuristic_rest: False
  debug: False
  prob_obs_enemy: 1.0
  action_mask: True

  # changed
  map_name: "10gen_terran"
  obs_own_pos: True
  capability_config:
    n_units: 15
    n_enemies: 16
    team_gen:
      dist_type: "weighted_teams"
      unit_types:
        - "marine"
        - "marauder"
        - "medivac"
      weights:
        - 0.45
        - 0.45
        - 0.1
      exception_unit_types:
        - "medivac"
      observe: True

    start_positions:
      dist_type: "surrounded_and_reflect"
      p: 0.5
      map_x: 32
      map_y: 32

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000